blank_issues_enabled: false
contact_links:
  - name: Questions or Discussion
    url: https://github.com/Johnesco/karaokedirectory/discussions
    about: Ask questions or start a discussion about this project
